### ISSUE TITLE
在popup.js 里 getBackgroundPage 并不能执行background.js里面的方法

### ISSUE THREAD

**Issue by liurenqiu520** [kinglisky/vtemp-chrome-extension#1]
这个怎么破？

**Comment by kinglisky** [comment]
能贴个 repo 具体描述下吗？
![](https://i.loli.net/2018/08/09/5b6c0681e0e87.jpg)

**Comment by liurenqiu520** [comment]
// background.js
function test()
{
    alert('我是background！');
}

// popup.js
var bg = chrome.extension.getBackgroundPage();
bg.test(); // 访问bg的函数

提示，bg不存在test方法。

**Comment by kinglisky** [comment]
```javascript
var bg = chrome.extension.getBackgroundPage();
// bg 是否是一个 BackgroundPage window 对象？
// bg 是否只返回 window 一些只读属性  ？
```
P.S 建议查一下 chrome extension 文档。

![](https://i.loli.net/2018/08/09/5b6c546117a1e.jpg)

这块我暂时不太清除，有空理一理。

**Comment by liurenqiu520** [comment]
我现在暂时的解决方案就是取消 src/background/index.js 被webpack打包，纯粹的把这个文件copy到dist/background.js。
