### ISSUE TITLE
大佬好,我在使用过程中出现下面报错

### ISSUE THREAD

**Issue by bxychy** [kinglisky/vtemp-chrome-extension#3]
Error in event handler for runtime.onInstalled: TypeError: Cannot read property 'onPageChanged' of undefined

`chrome.runtime.onInstalled.addListener(function(){
    chrome.declarativeContent.onPageChanged.removeRules(undefined, function(){
        chrome.declarativeContent.onPageChanged.addRules([
            {
                conditions: [
                    // 只有打开百度才显示pageAction
                    new chrome.declarativeContent.PageStateMatcher({pageUrl: {urlContains: 'baidu.com'}})
                ],
                actions: [new chrome.declarativeContent.ShowPageAction()]
            }
        ]);
    });
});`
代码是上面这段写在 background index.js里面

**Comment by kinglisky** [comment]
@zsychy 这块是你的业务逻辑还是？能具体描述下吗？
